name: Build and Deploy to AWS
run-name: ${{ github.actor }} is deploying to AWS

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.112.3'
          extended: true

      - name: Build
        run: hugo --minify
        working-directory: ./hugo

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
        working-directory: ./cdk

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: 'ap-southeast-2'

      - name: CDK diff
        run: cdk diff --all
        working-directory: ./cdk

      - name: CDK deploy
        run: cdk deploy --all
        working-directory: ./cdk
